databases:
  - name: task_manager
    plan: free
    databaseName: task_manager
    user: task_manager

services:
  - type: redis
    name: task_manager_redis
    ipAllowList: [ ] # only allow internal connections
    plan: free # optional (defaults to starter)
    maxmemoryPolicy: allkeys-lru

  - type: web
    plan: free
    name: task_manager
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: task_manager
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: REDIS_URL # this must match the name of the environment variable used in production.rb
        fromService:
          type: redis
          name: task_manager_redis
          property: connectionString